%%metro line: riboseq | Ribo-seq | #e6007e
%%metro line: rnaseq | RNA-seq | #2db572
%%metro file: bigwig_out | BW | Coverage
%%metro grid: preprocessing, alignment, novel_transcripts, quantification | 0,0
%%metro grid: psite | 1,0

graph LR
    subgraph preprocessing [Pre-processing]
        ribodetector[RiboDetector]
        bowtie2_rrna[Bowtie2]
        infer_strand[Infer strandedness]

        ribodetector -->|riboseq,rnaseq| infer_strand
        bowtie2_rrna -->|riboseq,rnaseq| infer_strand
    end

    subgraph alignment [Alignment]
        star[STAR]
        umi_dedup[Dedup]

        star -->|riboseq,rnaseq| umi_dedup
    end

    subgraph novel_transcripts [Novel transcripts]
        stringtie[StringTie]
        gffcompare[GffCompare]

        stringtie -->|rnaseq| gffcompare
    end

    subgraph quantification [Quantification]
        genomecov[genomecov]

        genomecov -->|riboseq,rnaseq| bigwig_out
    end

    subgraph psite [P-site]
        ribowaltz[riboWaltz]
    end

    infer_strand -->|riboseq,rnaseq| star
    umi_dedup -->|rnaseq| stringtie
    umi_dedup -->|riboseq,rnaseq| genomecov
    umi_dedup -->|riboseq| ribowaltz
